// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/bank/v1beta1/tx.proto

#include "cosmos/bank/v1beta1/tx.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace cosmos {
namespace bank {
namespace v1beta1 {
template <typename>
PROTOBUF_CONSTEXPR MsgSend::MsgSend(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.amount_)*/{}
  , /*decltype(_impl_.from_address_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.to_address_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgSendDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgSendDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgSendDefaultTypeInternal() {}
  union {
    MsgSend _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgSendDefaultTypeInternal _MsgSend_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgSendResponse::MsgSendResponse(
    ::_pbi::ConstantInitialized) {}
struct MsgSendResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgSendResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgSendResponseDefaultTypeInternal() {}
  union {
    MsgSendResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgSendResponseDefaultTypeInternal _MsgSendResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgMultiSend::MsgMultiSend(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.inputs_)*/{}
  , /*decltype(_impl_.outputs_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgMultiSendDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgMultiSendDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgMultiSendDefaultTypeInternal() {}
  union {
    MsgMultiSend _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgMultiSendDefaultTypeInternal _MsgMultiSend_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgMultiSendResponse::MsgMultiSendResponse(
    ::_pbi::ConstantInitialized) {}
struct MsgMultiSendResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgMultiSendResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgMultiSendResponseDefaultTypeInternal() {}
  union {
    MsgMultiSendResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgMultiSendResponseDefaultTypeInternal _MsgMultiSendResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgUpdateParams::MsgUpdateParams(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.authority_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.params_)*/nullptr} {}
struct MsgUpdateParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgUpdateParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgUpdateParamsDefaultTypeInternal() {}
  union {
    MsgUpdateParams _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgUpdateParamsDefaultTypeInternal _MsgUpdateParams_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgUpdateParamsResponse::MsgUpdateParamsResponse(
    ::_pbi::ConstantInitialized) {}
struct MsgUpdateParamsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgUpdateParamsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgUpdateParamsResponseDefaultTypeInternal() {}
  union {
    MsgUpdateParamsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgUpdateParamsResponseDefaultTypeInternal _MsgUpdateParamsResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgSetSendEnabled::MsgSetSendEnabled(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.send_enabled_)*/{}
  , /*decltype(_impl_.use_default_for_)*/{}
  , /*decltype(_impl_.authority_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MsgSetSendEnabledDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgSetSendEnabledDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgSetSendEnabledDefaultTypeInternal() {}
  union {
    MsgSetSendEnabled _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgSetSendEnabledDefaultTypeInternal _MsgSetSendEnabled_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR MsgSetSendEnabledResponse::MsgSetSendEnabledResponse(
    ::_pbi::ConstantInitialized) {}
struct MsgSetSendEnabledResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgSetSendEnabledResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgSetSendEnabledResponseDefaultTypeInternal() {}
  union {
    MsgSetSendEnabledResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgSetSendEnabledResponseDefaultTypeInternal _MsgSetSendEnabledResponse_default_instance_;
}  // namespace v1beta1
}  // namespace bank
}  // namespace cosmos
static ::_pb::Metadata file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[8];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cosmos_2fbank_2fv1beta1_2ftx_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cosmos_2fbank_2fv1beta1_2ftx_2eproto = nullptr;
const ::uint32_t TableStruct_cosmos_2fbank_2fv1beta1_2ftx_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSend, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSend, _impl_.from_address_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSend, _impl_.to_address_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSend, _impl_.amount_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSendResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgMultiSend, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgMultiSend, _impl_.inputs_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgMultiSend, _impl_.outputs_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgMultiSendResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgUpdateParams, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgUpdateParams, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgUpdateParams, _impl_.authority_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgUpdateParams, _impl_.params_),
    ~0u,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgUpdateParamsResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSetSendEnabled, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSetSendEnabled, _impl_.authority_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSetSendEnabled, _impl_.send_enabled_),
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSetSendEnabled, _impl_.use_default_for_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::cosmos::bank::v1beta1::MsgSetSendEnabledResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgSend)},
        { 11, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgSendResponse)},
        { 19, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgMultiSend)},
        { 29, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgMultiSendResponse)},
        { 37, 47, -1, sizeof(::cosmos::bank::v1beta1::MsgUpdateParams)},
        { 49, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgUpdateParamsResponse)},
        { 57, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgSetSendEnabled)},
        { 68, -1, -1, sizeof(::cosmos::bank::v1beta1::MsgSetSendEnabledResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::cosmos::bank::v1beta1::_MsgSend_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgSendResponse_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgMultiSend_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgMultiSendResponse_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgUpdateParams_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgUpdateParamsResponse_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgSetSendEnabled_default_instance_._instance,
    &::cosmos::bank::v1beta1::_MsgSetSendEnabledResponse_default_instance_._instance,
};
const char descriptor_table_protodef_cosmos_2fbank_2fv1beta1_2ftx_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\034cosmos/bank/v1beta1/tx.proto\022\023cosmos.b"
    "ank.v1beta1\032\024gogoproto/gogo.proto\032\036cosmo"
    "s/base/v1beta1/coin.proto\032\036cosmos/bank/v"
    "1beta1/bank.proto\032\031cosmos_proto/cosmos.p"
    "roto\032\027cosmos/msg/v1/msg.proto\032\021amino/ami"
    "no.proto\"\233\002\n\007MsgSend\022;\n\014from_address\030\001 \001"
    "(\tB\030\322\264-\024cosmos.AddressStringR\013fromAddres"
    "s\0227\n\nto_address\030\002 \001(\tB\030\322\264-\024cosmos.Addres"
    "sStringR\ttoAddress\022h\n\006amount\030\003 \003(\0132\031.cos"
    "mos.base.v1beta1.CoinB5\310\336\037\000\252\337\037(github.co"
    "m/cosmos/cosmos-sdk/types.Coins\250\347\260*\001R\006am"
    "ount:0\210\240\037\000\350\240\037\000\202\347\260*\014from_address\212\347\260*\022cosm"
    "os-sdk/MsgSend\"\021\n\017MsgSendResponse\"\274\001\n\014Ms"
    "gMultiSend\022=\n\006inputs\030\001 \003(\0132\032.cosmos.bank"
    ".v1beta1.InputB\t\310\336\037\000\250\347\260*\001R\006inputs\022@\n\007out"
    "puts\030\002 \003(\0132\033.cosmos.bank.v1beta1.OutputB"
    "\t\310\336\037\000\250\347\260*\001R\007outputs:+\350\240\037\000\202\347\260*\006inputs\212\347\260*"
    "\027cosmos-sdk/MsgMultiSend\"\026\n\024MsgMultiSend"
    "Response\"\277\001\n\017MsgUpdateParams\0226\n\tauthorit"
    "y\030\001 \001(\tB\030\322\264-\024cosmos.AddressStringR\tautho"
    "rity\022>\n\006params\030\002 \001(\0132\033.cosmos.bank.v1bet"
    "a1.ParamsB\t\310\336\037\000\250\347\260*\001R\006params:4\202\347\260*\tautho"
    "rity\212\347\260*!cosmos-sdk/x/bank/MsgUpdatePara"
    "ms\"\031\n\027MsgUpdateParamsResponse\"\351\001\n\021MsgSet"
    "SendEnabled\0226\n\tauthority\030\001 \001(\tB\030\322\264-\024cosm"
    "os.AddressStringR\tauthority\022C\n\014send_enab"
    "led\030\002 \003(\0132 .cosmos.bank.v1beta1.SendEnab"
    "ledR\013sendEnabled\022&\n\017use_default_for\030\003 \003("
    "\tR\ruseDefaultFor:/\202\347\260*\tauthority\212\347\260*\034cos"
    "mos-sdk/MsgSetSendEnabled\"\033\n\031MsgSetSendE"
    "nabledResponse2\201\003\n\003Msg\022J\n\004Send\022\034.cosmos."
    "bank.v1beta1.MsgSend\032$.cosmos.bank.v1bet"
    "a1.MsgSendResponse\022Y\n\tMultiSend\022!.cosmos"
    ".bank.v1beta1.MsgMultiSend\032).cosmos.bank"
    ".v1beta1.MsgMultiSendResponse\022b\n\014UpdateP"
    "arams\022$.cosmos.bank.v1beta1.MsgUpdatePar"
    "ams\032,.cosmos.bank.v1beta1.MsgUpdateParam"
    "sResponse\022h\n\016SetSendEnabled\022&.cosmos.ban"
    "k.v1beta1.MsgSetSendEnabled\032..cosmos.ban"
    "k.v1beta1.MsgSetSendEnabledResponse\032\005\200\347\260"
    "*\001B\273\001\n\027com.cosmos.bank.v1beta1B\007TxProtoP"
    "\001Z)github.com/cosmos/cosmos-sdk/x/bank/t"
    "ypes\242\002\003CBX\252\002\023Cosmos.Bank.V1beta1\312\002\023Cosmo"
    "s\\Bank\\V1beta1\342\002\037Cosmos\\Bank\\V1beta1\\GPB"
    "Metadata\352\002\025Cosmos::Bank::V1beta1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_deps[6] =
    {
        &::descriptor_table_amino_2famino_2eproto,
        &::descriptor_table_cosmos_2fbank_2fv1beta1_2fbank_2eproto,
        &::descriptor_table_cosmos_2fbase_2fv1beta1_2fcoin_2eproto,
        &::descriptor_table_cosmos_2fmsg_2fv1_2fmsg_2eproto,
        &::descriptor_table_cosmos_5fproto_2fcosmos_2eproto,
        &::descriptor_table_gogoproto_2fgogo_2eproto,
};
static ::absl::once_flag descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto = {
    false,
    false,
    1800,
    descriptor_table_protodef_cosmos_2fbank_2fv1beta1_2ftx_2eproto,
    "cosmos/bank/v1beta1/tx.proto",
    &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
    descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_deps,
    6,
    8,
    schemas,
    file_default_instances,
    TableStruct_cosmos_2fbank_2fv1beta1_2ftx_2eproto::offsets,
    file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto,
    file_level_enum_descriptors_cosmos_2fbank_2fv1beta1_2ftx_2eproto,
    file_level_service_descriptors_cosmos_2fbank_2fv1beta1_2ftx_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter() {
  return &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cosmos_2fbank_2fv1beta1_2ftx_2eproto(&descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto);
namespace cosmos {
namespace bank {
namespace v1beta1 {
// ===================================================================

class MsgSend::_Internal {
 public:
};

void MsgSend::clear_amount() {
  _internal_mutable_amount()->Clear();
}
MsgSend::MsgSend(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgSend)
}
MsgSend::MsgSend(const MsgSend& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgSend* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.amount_){from._impl_.amount_}
    , decltype(_impl_.from_address_) {}

    , decltype(_impl_.to_address_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.from_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.from_address_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_from_address().empty()) {
    _this->_impl_.from_address_.Set(from._internal_from_address(), _this->GetArenaForAllocation());
  }
  _impl_.to_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.to_address_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_to_address().empty()) {
    _this->_impl_.to_address_.Set(from._internal_to_address(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgSend)
}

inline void MsgSend::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.amount_){arena}
    , decltype(_impl_.from_address_) {}

    , decltype(_impl_.to_address_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.from_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.from_address_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.to_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.to_address_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MsgSend::~MsgSend() {
  // @@protoc_insertion_point(destructor:cosmos.bank.v1beta1.MsgSend)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgSend::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_amount()->~RepeatedPtrField();
  _impl_.from_address_.Destroy();
  _impl_.to_address_.Destroy();
}

void MsgSend::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgSend::Clear() {
// @@protoc_insertion_point(message_clear_start:cosmos.bank.v1beta1.MsgSend)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_amount()->Clear();
  _impl_.from_address_.ClearToEmpty();
  _impl_.to_address_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgSend::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string from_address = 1 [json_name = "fromAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_from_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cosmos.bank.v1beta1.MsgSend.from_address"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string to_address = 2 [json_name = "toAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_to_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cosmos.bank.v1beta1.MsgSend.to_address"));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .cosmos.base.v1beta1.Coin amount = 3 [json_name = "amount", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins", (.amino.dont_omitempty) = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_amount(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* MsgSend::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cosmos.bank.v1beta1.MsgSend)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string from_address = 1 [json_name = "fromAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_from_address().empty()) {
    const std::string& _s = this->_internal_from_address();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "cosmos.bank.v1beta1.MsgSend.from_address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string to_address = 2 [json_name = "toAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_to_address().empty()) {
    const std::string& _s = this->_internal_to_address();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "cosmos.bank.v1beta1.MsgSend.to_address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // repeated .cosmos.base.v1beta1.Coin amount = 3 [json_name = "amount", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins", (.amino.dont_omitempty) = true];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_amount_size()); i < n; i++) {
    const auto& repfield = this->_internal_amount(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cosmos.bank.v1beta1.MsgSend)
  return target;
}

::size_t MsgSend::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cosmos.bank.v1beta1.MsgSend)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .cosmos.base.v1beta1.Coin amount = 3 [json_name = "amount", (.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins", (.amino.dont_omitempty) = true];
  total_size += 1UL * this->_internal_amount_size();
  for (const auto& msg : this->_internal_amount()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string from_address = 1 [json_name = "fromAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_from_address().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_from_address());
  }

  // string to_address = 2 [json_name = "toAddress", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_to_address().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_to_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgSend::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgSend::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgSend::GetClassData() const { return &_class_data_; }


void MsgSend::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgSend*>(&to_msg);
  auto& from = static_cast<const MsgSend&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cosmos.bank.v1beta1.MsgSend)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_amount()->MergeFrom(from._internal_amount());
  if (!from._internal_from_address().empty()) {
    _this->_internal_set_from_address(from._internal_from_address());
  }
  if (!from._internal_to_address().empty()) {
    _this->_internal_set_to_address(from._internal_to_address());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgSend::CopyFrom(const MsgSend& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cosmos.bank.v1beta1.MsgSend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSend::IsInitialized() const {
  return true;
}

void MsgSend::InternalSwap(MsgSend* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_amount()->InternalSwap(other->_internal_mutable_amount());
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.from_address_, lhs_arena,
                                       &other->_impl_.from_address_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.to_address_, lhs_arena,
                                       &other->_impl_.to_address_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgSend::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[0]);
}
// ===================================================================

class MsgSendResponse::_Internal {
 public:
};

MsgSendResponse::MsgSendResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgSendResponse)
}
MsgSendResponse::MsgSendResponse(const MsgSendResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MsgSendResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgSendResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgSendResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgSendResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgSendResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[1]);
}
// ===================================================================

class MsgMultiSend::_Internal {
 public:
};

void MsgMultiSend::clear_inputs() {
  _internal_mutable_inputs()->Clear();
}
void MsgMultiSend::clear_outputs() {
  _internal_mutable_outputs()->Clear();
}
MsgMultiSend::MsgMultiSend(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgMultiSend)
}
MsgMultiSend::MsgMultiSend(const MsgMultiSend& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgMultiSend* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.inputs_){from._impl_.inputs_}
    , decltype(_impl_.outputs_){from._impl_.outputs_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgMultiSend)
}

inline void MsgMultiSend::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.inputs_){arena}
    , decltype(_impl_.outputs_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MsgMultiSend::~MsgMultiSend() {
  // @@protoc_insertion_point(destructor:cosmos.bank.v1beta1.MsgMultiSend)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgMultiSend::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_inputs()->~RepeatedPtrField();
  _internal_mutable_outputs()->~RepeatedPtrField();
}

void MsgMultiSend::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgMultiSend::Clear() {
// @@protoc_insertion_point(message_clear_start:cosmos.bank.v1beta1.MsgMultiSend)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_inputs()->Clear();
  _internal_mutable_outputs()->Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgMultiSend::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .cosmos.bank.v1beta1.Input inputs = 1 [json_name = "inputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_inputs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .cosmos.bank.v1beta1.Output outputs = 2 [json_name = "outputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_outputs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* MsgMultiSend::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cosmos.bank.v1beta1.MsgMultiSend)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .cosmos.bank.v1beta1.Input inputs = 1 [json_name = "inputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_inputs_size()); i < n; i++) {
    const auto& repfield = this->_internal_inputs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .cosmos.bank.v1beta1.Output outputs = 2 [json_name = "outputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_outputs_size()); i < n; i++) {
    const auto& repfield = this->_internal_outputs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cosmos.bank.v1beta1.MsgMultiSend)
  return target;
}

::size_t MsgMultiSend::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cosmos.bank.v1beta1.MsgMultiSend)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .cosmos.bank.v1beta1.Input inputs = 1 [json_name = "inputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  total_size += 1UL * this->_internal_inputs_size();
  for (const auto& msg : this->_internal_inputs()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .cosmos.bank.v1beta1.Output outputs = 2 [json_name = "outputs", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  total_size += 1UL * this->_internal_outputs_size();
  for (const auto& msg : this->_internal_outputs()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgMultiSend::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgMultiSend::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgMultiSend::GetClassData() const { return &_class_data_; }


void MsgMultiSend::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgMultiSend*>(&to_msg);
  auto& from = static_cast<const MsgMultiSend&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cosmos.bank.v1beta1.MsgMultiSend)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_inputs()->MergeFrom(from._internal_inputs());
  _this->_internal_mutable_outputs()->MergeFrom(from._internal_outputs());
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgMultiSend::CopyFrom(const MsgMultiSend& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cosmos.bank.v1beta1.MsgMultiSend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgMultiSend::IsInitialized() const {
  return true;
}

void MsgMultiSend::InternalSwap(MsgMultiSend* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_inputs()->InternalSwap(other->_internal_mutable_inputs());
  _internal_mutable_outputs()->InternalSwap(other->_internal_mutable_outputs());
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgMultiSend::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[2]);
}
// ===================================================================

class MsgMultiSendResponse::_Internal {
 public:
};

MsgMultiSendResponse::MsgMultiSendResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgMultiSendResponse)
}
MsgMultiSendResponse::MsgMultiSendResponse(const MsgMultiSendResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MsgMultiSendResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgMultiSendResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgMultiSendResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgMultiSendResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgMultiSendResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[3]);
}
// ===================================================================

class MsgUpdateParams::_Internal {
 public:
  using HasBits = decltype(std::declval<MsgUpdateParams>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(MsgUpdateParams, _impl_._has_bits_);
  static const ::cosmos::bank::v1beta1::Params& params(const MsgUpdateParams* msg);
  static void set_has_params(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::cosmos::bank::v1beta1::Params&
MsgUpdateParams::_Internal::params(const MsgUpdateParams* msg) {
  return *msg->_impl_.params_;
}
void MsgUpdateParams::clear_params() {
  if (_impl_.params_ != nullptr) _impl_.params_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
MsgUpdateParams::MsgUpdateParams(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgUpdateParams)
}
MsgUpdateParams::MsgUpdateParams(const MsgUpdateParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgUpdateParams* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.authority_) {}

    , decltype(_impl_.params_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.authority_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authority_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_authority().empty()) {
    _this->_impl_.authority_.Set(from._internal_authority(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.params_ = new ::cosmos::bank::v1beta1::Params(*from._impl_.params_);
  }
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgUpdateParams)
}

inline void MsgUpdateParams::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.authority_) {}

    , decltype(_impl_.params_){nullptr}
  };
  _impl_.authority_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authority_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MsgUpdateParams::~MsgUpdateParams() {
  // @@protoc_insertion_point(destructor:cosmos.bank.v1beta1.MsgUpdateParams)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgUpdateParams::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.authority_.Destroy();
  if (this != internal_default_instance()) delete _impl_.params_;
}

void MsgUpdateParams::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgUpdateParams::Clear() {
// @@protoc_insertion_point(message_clear_start:cosmos.bank.v1beta1.MsgUpdateParams)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.authority_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.params_ != nullptr);
    _impl_.params_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgUpdateParams::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_authority();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cosmos.bank.v1beta1.MsgUpdateParams.authority"));
        } else {
          goto handle_unusual;
        }
        continue;
      // .cosmos.bank.v1beta1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_params(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* MsgUpdateParams::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cosmos.bank.v1beta1.MsgUpdateParams)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authority().empty()) {
    const std::string& _s = this->_internal_authority();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "cosmos.bank.v1beta1.MsgUpdateParams.authority");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .cosmos.bank.v1beta1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::params(this),
        _Internal::params(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cosmos.bank.v1beta1.MsgUpdateParams)
  return target;
}

::size_t MsgUpdateParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cosmos.bank.v1beta1.MsgUpdateParams)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authority().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_authority());
  }

  // .cosmos.bank.v1beta1.Params params = 2 [json_name = "params", (.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.params_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgUpdateParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgUpdateParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgUpdateParams::GetClassData() const { return &_class_data_; }


void MsgUpdateParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgUpdateParams*>(&to_msg);
  auto& from = static_cast<const MsgUpdateParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cosmos.bank.v1beta1.MsgUpdateParams)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_authority().empty()) {
    _this->_internal_set_authority(from._internal_authority());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_params()->::cosmos::bank::v1beta1::Params::MergeFrom(
        from._internal_params());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgUpdateParams::CopyFrom(const MsgUpdateParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cosmos.bank.v1beta1.MsgUpdateParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgUpdateParams::IsInitialized() const {
  return true;
}

void MsgUpdateParams::InternalSwap(MsgUpdateParams* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authority_, lhs_arena,
                                       &other->_impl_.authority_, rhs_arena);
  swap(_impl_.params_, other->_impl_.params_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgUpdateParams::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[4]);
}
// ===================================================================

class MsgUpdateParamsResponse::_Internal {
 public:
};

MsgUpdateParamsResponse::MsgUpdateParamsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgUpdateParamsResponse)
}
MsgUpdateParamsResponse::MsgUpdateParamsResponse(const MsgUpdateParamsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MsgUpdateParamsResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgUpdateParamsResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgUpdateParamsResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgUpdateParamsResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgUpdateParamsResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[5]);
}
// ===================================================================

class MsgSetSendEnabled::_Internal {
 public:
};

void MsgSetSendEnabled::clear_send_enabled() {
  _internal_mutable_send_enabled()->Clear();
}
MsgSetSendEnabled::MsgSetSendEnabled(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgSetSendEnabled)
}
MsgSetSendEnabled::MsgSetSendEnabled(const MsgSetSendEnabled& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MsgSetSendEnabled* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.send_enabled_){from._impl_.send_enabled_}
    , decltype(_impl_.use_default_for_){from._impl_.use_default_for_}
    , decltype(_impl_.authority_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.authority_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authority_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_authority().empty()) {
    _this->_impl_.authority_.Set(from._internal_authority(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgSetSendEnabled)
}

inline void MsgSetSendEnabled::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.send_enabled_){arena}
    , decltype(_impl_.use_default_for_){arena}
    , decltype(_impl_.authority_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.authority_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.authority_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MsgSetSendEnabled::~MsgSetSendEnabled() {
  // @@protoc_insertion_point(destructor:cosmos.bank.v1beta1.MsgSetSendEnabled)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MsgSetSendEnabled::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_send_enabled()->~RepeatedPtrField();
  _internal_mutable_use_default_for()->~RepeatedPtrField();
  _impl_.authority_.Destroy();
}

void MsgSetSendEnabled::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MsgSetSendEnabled::Clear() {
// @@protoc_insertion_point(message_clear_start:cosmos.bank.v1beta1.MsgSetSendEnabled)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_send_enabled()->Clear();
  _internal_mutable_use_default_for()->Clear();
  _impl_.authority_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgSetSendEnabled::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_authority();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cosmos.bank.v1beta1.MsgSetSendEnabled.authority"));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated .cosmos.bank.v1beta1.SendEnabled send_enabled = 2 [json_name = "sendEnabled"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_send_enabled(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated string use_default_for = 3 [json_name = "useDefaultFor"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_use_default_for();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "cosmos.bank.v1beta1.MsgSetSendEnabled.use_default_for"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* MsgSetSendEnabled::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cosmos.bank.v1beta1.MsgSetSendEnabled)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authority().empty()) {
    const std::string& _s = this->_internal_authority();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "cosmos.bank.v1beta1.MsgSetSendEnabled.authority");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .cosmos.bank.v1beta1.SendEnabled send_enabled = 2 [json_name = "sendEnabled"];
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_send_enabled_size()); i < n; i++) {
    const auto& repfield = this->_internal_send_enabled(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated string use_default_for = 3 [json_name = "useDefaultFor"];
  for (int i = 0, n = this->_internal_use_default_for_size(); i < n; ++i) {
    const auto& s = this->_internal_use_default_for(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "cosmos.bank.v1beta1.MsgSetSendEnabled.use_default_for");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cosmos.bank.v1beta1.MsgSetSendEnabled)
  return target;
}

::size_t MsgSetSendEnabled::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cosmos.bank.v1beta1.MsgSetSendEnabled)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .cosmos.bank.v1beta1.SendEnabled send_enabled = 2 [json_name = "sendEnabled"];
  total_size += 1UL * this->_internal_send_enabled_size();
  for (const auto& msg : this->_internal_send_enabled()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated string use_default_for = 3 [json_name = "useDefaultFor"];
  total_size += 1 * ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_internal_use_default_for().size());
  for (int i = 0, n = _internal_use_default_for().size(); i < n; ++i) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        _internal_use_default_for().Get(i));
  }

  // string authority = 1 [json_name = "authority", (.cosmos_proto.scalar) = "cosmos.AddressString"];
  if (!this->_internal_authority().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_authority());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgSetSendEnabled::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MsgSetSendEnabled::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgSetSendEnabled::GetClassData() const { return &_class_data_; }


void MsgSetSendEnabled::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MsgSetSendEnabled*>(&to_msg);
  auto& from = static_cast<const MsgSetSendEnabled&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cosmos.bank.v1beta1.MsgSetSendEnabled)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_send_enabled()->MergeFrom(from._internal_send_enabled());
  _this->_internal_mutable_use_default_for()->MergeFrom(from._internal_use_default_for());
  if (!from._internal_authority().empty()) {
    _this->_internal_set_authority(from._internal_authority());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MsgSetSendEnabled::CopyFrom(const MsgSetSendEnabled& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cosmos.bank.v1beta1.MsgSetSendEnabled)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSetSendEnabled::IsInitialized() const {
  return true;
}

void MsgSetSendEnabled::InternalSwap(MsgSetSendEnabled* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_send_enabled()->InternalSwap(other->_internal_mutable_send_enabled());
  _internal_mutable_use_default_for()->InternalSwap(
      other->_internal_mutable_use_default_for());
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.authority_, lhs_arena,
                                       &other->_impl_.authority_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgSetSendEnabled::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[6]);
}
// ===================================================================

class MsgSetSendEnabledResponse::_Internal {
 public:
};

MsgSetSendEnabledResponse::MsgSetSendEnabledResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:cosmos.bank.v1beta1.MsgSetSendEnabledResponse)
}
MsgSetSendEnabledResponse::MsgSetSendEnabledResponse(const MsgSetSendEnabledResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MsgSetSendEnabledResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:cosmos.bank.v1beta1.MsgSetSendEnabledResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgSetSendEnabledResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgSetSendEnabledResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgSetSendEnabledResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_getter, &descriptor_table_cosmos_2fbank_2fv1beta1_2ftx_2eproto_once,
      file_level_metadata_cosmos_2fbank_2fv1beta1_2ftx_2eproto[7]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta1
}  // namespace bank
}  // namespace cosmos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgSend*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgSend >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgSend >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgSendResponse*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgSendResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgSendResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgMultiSend*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgMultiSend >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgMultiSend >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgMultiSendResponse*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgMultiSendResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgMultiSendResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgUpdateParams*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgUpdateParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgUpdateParams >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgUpdateParamsResponse*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgUpdateParamsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgUpdateParamsResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgSetSendEnabled*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgSetSendEnabled >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgSetSendEnabled >(arena);
}
template<> PROTOBUF_NOINLINE ::cosmos::bank::v1beta1::MsgSetSendEnabledResponse*
Arena::CreateMaybeMessage< ::cosmos::bank::v1beta1::MsgSetSendEnabledResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::bank::v1beta1::MsgSetSendEnabledResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
